
@uri = http://localhost:3000/
###
GET {{uri}}api/players


###
GET {{uri}}api/players/3

###

POST {{uri}}api/players
Content-Type:  application/json

{
    "no"    : 12,
    "name" : "zhaohan",
    "age" : "U8",
    "item" : ["3x3","2x2","pyramid"]
}

###
PUT {{uri}}api/players
Content-Type:  application/json

{
    "no"    : 1,
    "name" : "zhaohan",
    "item" : ["3x3"]
}


###
DELETE {{uri}}api/players/12



# ----------------------------------------------------------------------------------------
@uri = http://localhost:3000/
###
GET {{uri}}api/results


###
DELETE {{uri}}api/results

###
POST {{uri}}api/results
Content-Type:  application/json

{
    "age": "U8",
    "best": 832,
    "id": 1,
    "item": "pyramid",
    "name": "赵晗",
    "rank": "-",
    "result": 156,
    "round": "final",
    "t1": 899,
    "t2": 1835,
    "t3": 1562,
    "t4": 832,
    "t5": 1530
}

###
POST {{uri}}api/results/delete
Content-Type:  application/json

{
    "id": 1,
    "round": "first",
    "item" : "3x3"
}


###
GET  {{uri}}api/adminusers

###
GET  {{uri}}api/normalusers


###
GET  {{uri}}api/vericode